# Generated by Django 3.1.7 on 2021-06-18 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('adress', models.CharField(max_length=200, verbose_name='Adress')),
                ('mother_name', models.CharField(max_length=200, verbose_name='Mother Name')),
                ('father_name', models.CharField(max_length=200, verbose_name='Father Name')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('French', 'French'), ('Physical', 'Physical')], max_length=200, verbose_name='Subject')),
                ('value', models.IntegerField(verbose_name='Notation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='examples.student')),
            ],
            options={
                'verbose_name': 'Les notes',
                'verbose_name_plural': 'Les notes',
            },
        ),
    ]
